server.port=8081

spring.application.name=noxa-bank-backend

spring.datasource.url=jdbc:postgresql://localhost:5433/noxa_bank
spring.datasource.username=noxa
spring.datasource.password=noxa_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false